[versions]
android-plugin = "7.0.3"
androidx-appcompat = "1.3.1"
androidx-cardview = "1.0.0"
androidx-constraintlayout = "2.1.1"
androidx-core = "1.7.0"
androidx-core-role = "1.0.0"
androidx-fragment = "1.3.6"
androidx-lifecycle = "2.4.0"
androidx-recyclerview = "1.2.1"
androidx-room = "2.3.0"
androidx-tvprovider = "1.1.0-alpha01"
koin = "3.1.3"
kotlin = "1.5.31"
kotlin-ksp = "1.5.31-1.0.0"

[plugins]
android-app = { id = "com.android.application", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-role = { module = "androidx.core:core-role", version.ref = "androidx-core-role" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-tvprovider = { module = "androidx.tvprovider:tvprovider", version.ref = "androidx-tvprovider" }
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
