[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.3.1" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version = "1.0.0" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.1" }
androidx-core-core = { group = "androidx.core", name = "core-ktx", version = "1.7.0" }
androidx-core-role = { group = "androidx.core", name = "core-role", version = "1.0.0" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version = "1.3.6" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version = "2.4.0" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.2.1" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version = "2.3.0" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version = "2.3.0" }
androidx-tvprovider = { group = "androidx.tvprovider", name = "tvprovider", version = "1.1.0-alpha01" }
koin = { group = "io.insert-koin", name = "koin-android", version = "3.1.3" }
