[libraries]
androidx-core-core = { group = "androidx.core", name = "core-ktx", version = "1.3.2" }
androidx-core-role = { group = "androidx.core", name = "core-role", version = "1.0.0" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version = "1.0.0" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version = "1.3.3" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version = "1.0.0" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.0.4" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version = "2.3.1" }
androidx-tvprovider = { group = "androidx.tvprovider", name = "tvprovider", version = "1.0.0" }
